version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge